### ISSUE TITLE
fix createTrips method in input.py

### ISSUE THREAD

**Issue by LorenzKr** [Tezzmo/PDS_Project#1]
![grafik](https://user-images.githubusercontent.com/53060621/80805873-6fda2780-8bb9-11ea-8f84-1e9b59826777.png)

The createTrip method uses wrong start, if correct start point for same bikeNumber is missing and generates a not existing trip, with a far too high duration.

**Comment by jonfro** [comment]
Fixed with commit to DataExploration branch.

**Comment by LorenzKr** [comment]
Die hinzugefügten spalten sind noch 'objects' dtypes. Das ist unschön. Entweder als category oder ints speichern. Spart viel Speicherplatz.

**Comment by jonfro** [comment]
@Tezzmo Kümmer ich mich drum. Klappt die Slack Integration jetzt?

**Comment by LorenzKr** [comment]
Filter first by bike number. Then by date.
