### ISSUE TITLE
2c) Build Heatmap 

### ISSUE THREAD

**Issue by LorenzKr** [Tezzmo/PDS_Project#8]
Create a heatmap based on an interesting aspect of the data, e.g., end locations of trips shortly 
before the start of a major public event.

Which interesting event happens in marburg

**Comment by Fabian1Rehn** [comment]
- Eventkalender:
https://www.marburg.de/kultur-tourismus/veranstaltungen/veranstaltungskalender/

- Only the bigger ones

**Comment by LorenzKr** [comment]
https://www.marburg-net.de/feste.html
